#!/usr/bin/env python3
"""Regenerate src/lib/geo/dotfield-grid.ts, the land mask behind the home page's dot map (DotMap).

  python3 scripts/gen-dotfield.py california.geojson us-states.json > src/lib/geo/dotfield-grid.ts

Inputs (public domain / open data, downloaded once):
  https://raw.githubusercontent.com/glynnbird/usstatesgeojson/master/california.geojson
  https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json

The projection constants here MUST match GRID in src/lib/geo/dotfield.ts.
"""
import json, math, sys

W, H, STEP = 1260, 460, 10
MAX_LAT, MIN_LAT, LNG0 = 42.6, 31.9, -131.5
K = math.cos(37.3 * math.pi / 180)
S = H / (MAX_LAT - MIN_LAT)

def pip(ring, la, ln):
    c = False
    for i in range(len(ring)):
        x1, y1 = ring[i]; x2, y2 = ring[i - 1]
        if (y1 > la) != (y2 > la) and ln < (x2 - x1) * (la - y1) / (y2 - y1) + x1:
            c = not c
    return c

ca = json.load(open(sys.argv[1])); ca = ca["features"][0] if "features" in ca else ca
ca_ring = max(ca["geometry"]["coordinates"], key=lambda p: len(p[0]))[0]
others = []
for f in json.load(open(sys.argv[2]))["features"]:
    if f["properties"].get("name") == "California":
        continue
    g = f["geometry"]
    for p in (g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]):
        r = p[0]
        others.append(((min(q[1] for q in r), max(q[1] for q in r), min(q[0] for q in r), max(q[0] for q in r)), r))

rows = []
for gy in range(0, H + 1, STEP):
    row = []
    for gx in range(0, W + 1, STEP):
        x = gx + (STEP / 2 if (gy // STEP) % 2 else 0)
        la, ln = MAX_LAT - gy / S, LNG0 + x / (K * S)
        if pip(ca_ring, la, ln): row.append("2")
        elif any(b[0] <= la <= b[1] and b[2] <= ln <= b[3] and pip(r, la, ln) for b, r in others): row.append("1")
        else: row.append("0")
    rows.append("".join(row))

print("// GENERATED by scripts/gen-dotfield.py. Do not edit by hand.")
print("// One string per dot row: 0 = ocean / Mexico, 1 = a neighbouring state, 2 = California.")
print("export const DOT_ROWS: readonly string[] = [")
for r in rows:
    print(f'  "{r}",')
print("];")
